### PR TITLE
Moved some table constructs to abstracts.

### PR DESCRIPTION
**Pull request by nanjizal**
**Moved some table constructs to abstracts.**

_advantages:_
Reader.read is now much cleaner to read, once you cope with the abstract use, since I moved table construction.
Reader line count reduced - with simple bytes or input -> typedef moved to an abstracts around the typedef. 
More complex table readers not changed at moment, since they are more than just data structures.

_unrelated comments:_
I have hxswfml with tiny bit more code, and tiny bit less in places than the version your work is based on, and I am sure I had it compiling at one stage fine. But thought I should start with fiddling with your version, and try to work out how to add the stuff back later after maybe getting my head deeper into the code, so started with making fairly superficial adjustments hopefully in the direction of clarity.

### CODE REVIEW

**Comment by nanjizal** [comment]
Really would prefer if the code base used 4 spaces tab indent throughout I find tabs rather unpredictable between systems and prefer spaces, happy to make a pull with that changed but totally understand if your keen not to change that. Normally you can specify softtabs with 4 spaces in IDE's.

**Comment by nanjizal** [comment]
needs haxelib.json to use with haxelib git since files are in src.

**Comment by nanjizal** [comment]
Rename Main.hx to CanvasTest.hx so that haxelib use from Kha does not try to use it as Main.

**Comment by cambiata** [comment]
Thank you, Nanji! 
I've emailed Jan - let's hope that he responds about the MIT license...

**Pull request merged**
